server {
    listen 80;

    resolver 10.43.0.10 valid=10s;
    resolver_timeout 5s;

    root /usr/share/nginx/html;
    index index.html;

    # --- FRONTEND (SPA) ---
    location / {
        try_files $uri $uri/ /index.html;
    }
}
