name: Frontend STAGING

on:
  pull_request:
    branches:
      - staging
    types:
      - closed

permissions:
  contents: write
  pull-requests: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: jaffleman971/maptdp-frontend

jobs:

  validate-source:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Validate source
        run: |
          SOURCE="${{ github.event.pull_request.head.ref }}"

          if [ "$SOURCE" != "dev" ]; then
            echo "Only dev can be merged into staging"
            exit 1
          fi

  prepare:
    if: github.event.pull_request.merged == true
  
    needs:
      - validate-source
  
    runs-on: ubuntu-latest
  
    outputs:
      sha: ${{ steps.sha.outputs.sha }}
  
    steps:
      - id: sha
        run: |
          echo "sha=$(date +%s)" >> $GITHUB_OUTPUT

  retag-staging:
    needs:
      - prepare
  
    runs-on: ubuntu-latest
  
    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Pull dev image
        run: |
          docker pull \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-latest
  
      - name: Tag staging image
        run: |
          docker tag \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-sha-${{ needs.prepare.outputs.sha }}
  
          docker tag \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev-latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-latest
  
      - name: Push staging image
        run: |
          docker push \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-sha-${{ needs.prepare.outputs.sha }}
  
          docker push \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging-latest

  create-pr-prod:
    needs:
      - retag-staging

    runs-on: ubuntu-latest

    steps:
      - name: Create PR to prod
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'staging',
              base: 'prod',
              state: 'open'
            });

            if (prs.length === 0) {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Promote staging → prod',
                head: 'staging',
                base: 'prod',
                body: 'Automatic promotion'
              });
            }
